//Estas variables (o constantes) nos permiten definir
//el nombre de una mutacion reemplazando, esto se utiliza
//para evitar posibles errores tipograficos entre componentes
export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE'

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE'

export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_CART = 'UPDATE_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const ADD_SHIPPING_ADDRESS = 'ADD_SHIPPING_ADDRESS'
export const ADD_SHIPPING_ADDRESS_SUCCESS = 'ADD_SHIPPING_ADDRESS_SUCCESS'
export const ADD_SHIPPING_METHOD = 'ADD_SHIPPING_METHOD'
export const ALL_SHIPPING_METHODS = 'ALL_SHIPPING_METHODS'
export const ALL_SHIPPING_METHODS_SUCCESS = 'ALL_SHIPPING_METHODS_SUCCESS'
export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD'
export const ALL_PAYMENT_METHODS = 'ALL_PAYMENT_METHODS'
export const ALL_PAYMENT_METHODS_SUCCESS = 'ALL_PAYMENT_METHODS_SUCCESS'
export const PROCESS_PAYMENT = 'PROCESS_PAYMENT'
export const PROCESS_PAYMENT_SUCCESS = 'PROCESS_PAYMENT_SUCCESS'
export const PROCESS_PAYMENT_FAILURE = 'PROCESS_PAYMENT_FAILURE'
export const CONFIRM_ORDER = 'CONFIRM_ORDER'
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS'
export const COMPLETE_ORDER = 'COMPLETE_ORDER'
export const COMPLETE_ORDER_SUCCESS = 'COMPLETE_ORDER_SUCCESS'

export const ALL_MANUFACTURERS = 'ALL_MANUFACTURER'
export const ALL_MANUFACTURERS_SUCCESS = 'ALL_MANUFACTURER_SUCCESS'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'