//Estas variables (o constantes) nos permiten definir
//el nombre de una mutacion reemplazando, esto se utiliza
//para evitar posibles errores tipograficos entre componentes
export const PAGE_TITLE = 'PAGE_TITLE';
export const PAGE_ICON = 'PAGE_ICON';
export const PAGE_COVER = 'PAGE_COVER';

export const ALL_MANUFACTURERS = 'ALL_MANUFACTURER';
export const ALL_MANUFACTURERS_SUCCESS = 'ALL_MANUFACTURER_SUCCESS';
export const ALL_MANUFACTURERS_FAILURE = 'ALL_MANUFACTURER_FAILURE';

export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE';

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID';
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS';
export const PRODUCT_BY_ID_FAILURE = 'PRODUCT_BY_ID_FAILURE';

export const CUSTOM_PRODUCT = 'CUSTOM_PRODUCT';
export const CUSTOM_PRODUCT_SUCCESS = 'CUSTOM_PRODUCT_SUCCESS';
export const CUSTOM_PRODUCT_FAILURE = 'CUSTOM_PRODUCT_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const ALL_SHIPPING_METHODS = 'ALL_SHIPPING_METHODS';
export const ALL_SHIPPING_METHODS_SUCCESS = 'ALL_SHIPPING_METHODS_SUCCESS';
export const ALL_SHIPPING_METHODS_FAILURE = 'ALL_SHIPPING_METHODS_FAILURE';

export const CHECKOUT_OPTIONS = 'CHECKOUT_OPTIONS';
export const CHECKOUT_OPTIONS_SUCCESS = 'CHECKOUT_OPTIONS_SUCCESS';
export const CHECKOUT_OPTIONS_FAILURE = 'CHECKOUT_OPTIONS_FAILURE';

export const ALL_PAYMENT_METHODS = 'ALL_PAYMENT_METHODS';
export const ALL_PAYMENT_METHODS_SUCCESS = 'ALL_PAYMENT_METHODS_SUCCESS'
export const ALL_PAYMENT_METHODS_FAILURE = 'ALL_PAYMENT_METHODS_FAILURE';

export const ADD_SHIPPING_ADDRESS = 'ADD_SHIPPING_ADDRESS';
export const ADD_SHIPPING_METHOD = 'ADD_SHIPPING_METHOD';
export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD';
export const ADD_EXPRESS_SHIPPING = 'ADD_EXPRESS_SHIPPING';
export const ADD_DELIVERY_DATE = 'ADD_DELIVERY_DATE';
export const ADD_DELIVERY_TIME = 'ADD_DELIVERY_TIME';
export const ADD_COUPON = 'ADD_COUPON';
export const GET_COUPON_VALUE = 'GET_COUPON_VALUE';
export const GET_COUPON_VALUE_SUCCESS = 'GET_COUPON_VALUE_SUCCESS';
export const GET_COUPON_VALUE_FAILURE = 'GET_COUPON_VALUE_FAILURE';

export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS';
export const CONFIRM_ORDER_FAILURE = 'CONFIRM_ORDER_FAILURE';

export const PROCESS_PAYMENT = 'PROCESS_PAYMENT';
export const PROCESS_PAYMENT_SUCCESS = 'PROCESS_PAYMENT_SUCCESS';
export const PROCESS_PAYMENT_FAILURE = 'PROCESS_PAYMENT_FAILURE';

export const COMPLETE_ORDER = 'COMPLETE_ORDER';
export const COMPLETE_ORDER_SUCCESS = 'COMPLETE_ORDER_SUCCESS';
export const COMPLETE_ORDER_FAILURE = 'COMPLETE_ORDER_FAILURE';

export const ERROR_MSG = 'ERROR_MSG';
export const SUCCESS_MSG = 'SUCCESS_MSG';
