//export const API_BASE = "http://demo.gaiproject.com.ng/directus"
export const API_BASE = "http://localhost/directus/"
//export const API_ROOT = "http://demo.gaiproject.com.ng"
export const API_ROOT = "http://localhost/"
export const TOKEN = "vpqBqeRX4CGw2OgDdZxv9H26Rw8mIo4Z"
